version: 0.2
# env:
#    variables:
#         CACHE_CONTROL: "100"
#         S3_BUCKET: build-source-code
#         BUILD_ENV: dev

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing Dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Project..."
      - npm run build
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      # - aws s3 sync build/ s3://build-code-a1/client-khan --delete
      
      
artifacts:
  files:
    - "**/*"
  base-directory: build