version: 0.2
env:
   variables:
        CACHE_CONTROL: "100"
        S3_BUCKET: build-source-code
        BUILD_ENV: dev

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing Dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Project..."
      - npm run build
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 cp build/* s3://${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
      
artifacts:
  files:
    - '**/*'
  base-directory: 'build*'
  discard-paths: yes